// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp1MvcCrud.Data;

#nullable disable

namespace WebApp1MvcCrud.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    [Migration("20230606001840_Seed Student table")]
    partial class SeedStudenttable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp1MvcCrud.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Age")
                        .HasColumnType("smallint");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Grade")
                        .HasColumnType("real");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = (short)18,
                            Firstname = "Patricia",
                            Grade = 3.1f,
                            Lastname = "White",
                            RegDate = new DateTime(2023, 6, 5, 20, 18, 40, 86, DateTimeKind.Local).AddTicks(5680)
                        },
                        new
                        {
                            Id = 2,
                            Age = (short)21,
                            Firstname = "Alejandra",
                            Grade = 2.85f,
                            Lastname = "Ferguson",
                            RegDate = new DateTime(2023, 6, 5, 20, 18, 40, 86, DateTimeKind.Local).AddTicks(5743)
                        },
                        new
                        {
                            Id = 3,
                            Age = (short)22,
                            Firstname = "Bonnie",
                            Grade = 2.31f,
                            Lastname = "Kingsley",
                            RegDate = new DateTime(2023, 6, 5, 20, 18, 40, 86, DateTimeKind.Local).AddTicks(5747)
                        },
                        new
                        {
                            Id = 4,
                            Age = (short)17,
                            Firstname = "Michelle",
                            Grade = 3.22f,
                            Lastname = "Pate",
                            RegDate = new DateTime(2023, 6, 5, 20, 18, 40, 86, DateTimeKind.Local).AddTicks(5751)
                        },
                        new
                        {
                            Id = 5,
                            Age = (short)24,
                            Firstname = "Shirley ",
                            Grade = 3.38f,
                            Lastname = "Krug",
                            RegDate = new DateTime(2023, 6, 5, 20, 18, 40, 86, DateTimeKind.Local).AddTicks(5755)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
